"""Generate the dependency-extraction wrapper theory for ``reconcile``.

The generated theory imports every PROVED-eligible node's theory and, for each
node's named Isabelle ``fact``, asks Isabelle's kernel for the *real* immediate
named proof dependencies via ``Thm_Deps.thm_deps``. Those dependency names are
filtered down to the blueprint's own fact-name set (so library lemmas like
``Pure.protectI`` are dropped) and written to a TSV file -- batch
``isabelle build`` suppresses ``writeln`` stdout, so we mirror the proof-status
checker and emit results to a file the Python side reads back.

This module deliberately lives apart from :mod:`theory_gen` (which it imports
from) so the two features never edit a shared generator.
"""
from __future__ import annotations

from isabelle_blueprint.isabelle.theory_gen import (
    _import_name,
    _ml_string,
    group_facts_by_theory,
)
from isabelle_blueprint.model.project import BlueprintProject

# Marker emitted per node: ISABELLE_BLUEPRINT_DEPS<TAB>node_id<TAB>fact<TAB>dep,dep
DEPS_MARKER = "ISABELLE_BLUEPRINT_DEPS"


def generate_reconcile_theory(
    project: BlueprintProject,
    *,
    deps_file: str,
    theory_name: str = "Blueprint_Deps",
    default_import_session: str | None = None,
    nonce: str | None = None,
) -> str | None:
    """Return the source of a wrapper theory that extracts real proof deps.

    Returns ``None`` when the project has no PROVED-eligible node (i.e. no node
    carries a resolvable Isabelle ``fact``): there is nothing to reconcile, so
    no theory should be built.
    """
    grouped = group_facts_by_theory(project)
    if not grouped:
        return None

    imports = sorted(
        {
            _import_name(ref, default_import_session=default_import_session)
            for refs in grouped.values()
            for ref in refs
        }
    )
    if not imports:
        imports = ["Main"]

    # Stable, de-duplicated (node_id, fact) rows and the blueprint's own fact set.
    rows: list[tuple[str, str]] = []
    seen_nodes: set[str] = set()
    known_facts: set[str] = set()
    for theory in sorted(grouped):
        for ref in sorted(grouped[theory], key=lambda r: r.fact):
            known_facts.add(ref.fact)
            if ref.node_id in seen_nodes:
                continue
            seen_nodes.add(ref.node_id)
            rows.append((ref.node_id, ref.fact))

    lines: list[str] = []
    lines.append(f"theory {theory_name}")
    lines.append("  imports")
    for imp in imports:
        lines.append(f'    "{imp}"')
    lines.append("begin")
    lines.append("")
    lines.append("(* Auto-generated by IsabelleBlueprint. Do not edit by hand. *)")
    if nonce:
        # Perturb the source so ``isabelle build`` re-runs the ML (and rewrites
        # the deps file) instead of reusing a cached wrapper heap.
        lines.append(f"(* Run nonce: {_comment_escape(nonce)} *)")
    lines.append("")
    lines.extend(
        _deps_ml_block(
            rows=rows,
            known_facts=sorted(known_facts),
            deps_file=deps_file,
        )
    )
    lines.append("")
    lines.append("end")
    return "\n".join(lines) + "\n"


def _deps_ml_block(
    *,
    rows: list[tuple[str, str]],
    known_facts: list[str],
    deps_file: str,
) -> list[str]:
    """Render the ML block that writes one deps line per node to *deps_file*."""
    deps_path = _ml_string(deps_file)
    known_list = ", ".join(_ml_string(f) for f in known_facts)
    row_list = ",\n".join(
        f"    ({_ml_string(node_id)}, {_ml_string(fact)})" for node_id, fact in rows
    )
    return [
        "ML \\<open>",
        "let",
        f"  val known = Symset.make [{known_list}]",
        "  val ctxt = @{context}",
        "  val thy = Proof_Context.theory_of ctxt",
        "  fun deps_of fact =",
        "    (case try (Proof_Context.get_thm ctxt) fact of",
        "       NONE => []",
        "     | SOME thm =>",
        "         (case try (Thm_Deps.thm_deps thy) [thm] of",
        "            SOME d =>",
        "              map (fn (_, (n, _)) => n) d",
        "              |> filter (Symset.member known)",
        "              |> distinct (op =)",
        "          | NONE => []))",
        "  val rows = [",
        row_list,
        "  ]",
        "  fun render (node_id, fact) =",
        f'    "{DEPS_MARKER}\\t" ^ node_id ^ "\\t" ^ fact ^ "\\t" ^',
        '    space_implode "," (deps_of fact)',
        "in",
        f'  File.write (Path.explode {deps_path}) (cat_lines (map render rows) ^ "\\n")',
        "end",
        "\\<close>",
    ]


def _comment_escape(text: str) -> str:
    return text.replace("*)", "* )")


__all__ = ["DEPS_MARKER", "generate_reconcile_theory"]
