"""Generate an Isabelle theory that exercises every referenced fact.

The generated theory looks like::

    theory Blueprint_Check
      imports
        "Main"
        "Pythagoras.Triangles"
        "Pythagoras.Pythagoras"
    begin

    (* === Triangles === *)
    ML \\<open>val _ = Thm.prop_of @{thm Triangles.right_angle_def}\\<close>

    (* === Pythagoras === *)
    ML \\<open>val _ = Thm.prop_of @{thm Pythagoras.pythagoras_thm}\\<close>

    end

Running ``isabelle build`` on a session that includes this theory will fail if
any ``@{thm name}`` antiquotation cannot be resolved. For resolved facts the
generated ML also prints a machine-readable status line based on
``Thm_Deps.has_skip_proof`` and ``Thm_Deps.all_oracles`` so the Python checker
can distinguish merely-found facts from trusted ``proved`` facts.
"""
from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass

from isabelle_blueprint.model.node import BlueprintNode
from isabelle_blueprint.model.project import BlueprintProject


@dataclass(frozen=True)
class FactReference:
    """An (id, theory, fact-name) triple to render in the check theory."""

    node_id: str
    theory: str
    fact: str
    session: str | None = None


def group_facts_by_theory(
    project: BlueprintProject,
    *,
    include_node_ids: set[str] | None = None,
) -> dict[str, list[FactReference]]:
    """Return references grouped by their owning theory.

    Nodes without a resolvable ``isabelle:`` reference are skipped. When
    ``include_node_ids`` is provided, only nodes whose id is in that set are
    considered (used by the incremental checker to generate a wrapper theory
    that contains only the subset of facts that actually need re-checking).
    """
    grouped: dict[str, list[FactReference]] = defaultdict(list)
    for node in project.nodes:
        if include_node_ids is not None and node.id not in include_node_ids:
            continue
        ref = _resolve(node)
        if ref is None:
            continue
        grouped[ref.theory].append(ref)
    return dict(grouped)


def _resolve(node: BlueprintNode) -> FactReference | None:
    fact = node.isabelle.fact
    theory = node.isabelle.theory
    if not fact:
        return None
    if theory is None and "." in fact:
        theory = fact.rsplit(".", 1)[0]
    if theory is None:
        # No theory we can import; the checker would just fail.
        return None
    return FactReference(node_id=node.id, theory=theory, fact=fact, session=node.isabelle.session)


def generate_check_theory(
    project: BlueprintProject,
    *,
    theory_name: str = "Blueprint_Check",
    extra_imports: list[str] | None = None,
    emit_proof_status: bool = True,
    default_import_session: str | None = None,
    proof_status_file: str = "Blueprint_Proof_Status.tsv",
    generation_nonce: str | None = None,
    include_node_ids: set[str] | None = None,
) -> str:
    """Return the source of an Isabelle theory that references every fact.

    When ``include_node_ids`` is provided, only those nodes contribute facts to
    the generated theory. This is used by the incremental checker to ship a
    reduced wrapper containing just the changed/uncached subset.
    """
    grouped = group_facts_by_theory(project, include_node_ids=include_node_ids)
    imports = sorted(
        {
            _import_name(ref, default_import_session=default_import_session)
            for refs in grouped.values()
            for ref in refs
        }
    )
    if extra_imports:
        imports.extend(extra_imports)
    if not imports:
        imports = ["Main"]

    lines: list[str] = []
    lines.append(f"theory {theory_name}")
    lines.append("  imports")
    for imp in imports:
        lines.append(f'    "{imp}"')
    lines.append("begin")
    lines.append("")
    lines.append("(* Auto-generated by IsabelleBlueprint. Do not edit by hand. *)")
    if generation_nonce:
        lines.append(f"(* Check nonce: {_comment_escape(generation_nonce)} *)")
    lines.append("")
    proof_refs: list[FactReference] = []
    for theory in sorted(grouped):
        refs = grouped[theory]
        lines.append(f"(* === {theory} === *)")
        for ref in sorted(refs, key=lambda r: r.fact):
            if emit_proof_status:
                proof_refs.append(ref)
            else:
                lines.append(
                    f"ML \\<open>val _ = Thm.prop_of @{{thm {ref.fact}}}\\<close>  (* {ref.node_id} *)"
                )
        lines.append("")
    if emit_proof_status and proof_refs:
        lines.extend(_proof_status_ml_block(sorted(proof_refs, key=lambda r: (r.theory, r.fact)), proof_status_file=proof_status_file))
        lines.append("")
    lines.append("end")
    return "\n".join(lines) + "\n"


def _import_name(ref: FactReference, *, default_import_session: str | None = None) -> str:
    session = ref.session or default_import_session
    if not session:
        return ref.theory
    if ref.theory.startswith(f"{session}."):
        return ref.theory
    return f"{session}.{ref.theory}"


def _proof_status_ml_block(refs: list[FactReference], *, proof_status_file: str) -> list[str]:
    path = _ml_string(proof_status_file)
    row_lines = []
    for ref in refs:
        row_lines.append(f"    ({_ml_string(ref.node_id)}, {_ml_string(ref.fact)}, @{{thm {ref.fact}}})")
    rows = ",\n".join(row_lines)
    return [
        "ML \\<open>",
        "let",
        "  val rows = [",
        rows,
        "  ]",
        "  fun render (node_id, fact, thm) =",
        "    let",
        "      val thms = [thm]",
        "      val _ = Thm.prop_of thm",
        "      val oracles = Thm_Deps.all_oracles thms",
        "        |> map (fn ((name, _), _) => name)",
        "      val has_skip = Thm_Deps.has_skip_proof thms",
        "      val status = if has_skip orelse not (null oracles) then \"tainted\" else \"proved\"",
        "      val oracle_text = if null oracles then \"-\" else space_implode \",\" oracles",
        "    in",
        "      \"ISABELLE_BLUEPRINT_FACT\\t\" ^ node_id ^ \"\\t\" ^ fact ^ \"\\t\" ^ status ^ \"\\t\" ^ oracle_text",
        "    end",
        "in",
        f"  File.write (Path.explode {path}) (cat_lines (map render rows) ^ \"\\n\")",
        "end",
        "\\<close>",
    ]


def generate_check_root(
    session_name: str,
    *,
    wrapper_name: str = "Blueprint_Check_Wrapper",
    theory_name: str = "Blueprint_Check",
    session_deps: list[str] | None = None,
) -> str:
    """Return the contents of a ROOT file that wraps the user's session.

    The wrapper session inherits from ``session_name`` and adds the auto-generated
    ``Blueprint_Check`` theory. Writing this file alongside ``Blueprint_Check.thy``
    in the build directory lets ``isabelle build -d <build_dir>`` resolve the
    theory without modifying the user's own ROOT file.
    """
    deps = sorted({dep for dep in session_deps or [] if dep and dep != session_name})
    lines = [f"session {_root_string(wrapper_name)} = {_root_string(session_name)} +"]
    if deps:
        lines.append("  sessions")
        lines.extend(f"    {_root_string(dep)}" for dep in deps)
    lines.extend(["  theories", f"    {theory_name}"])
    return "\n".join(lines) + "\n"


def _ml_string(text: str) -> str:
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _root_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _comment_escape(text: str) -> str:
    return text.replace("*)", "* )")
