"""Best-effort import of Isabelle theory declarations into blueprint nodes."""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

DECLARATION_KINDS = ("lemma", "theorem", "corollary", "proposition", "definition")
_THEORY_RE = re.compile(r"(?m)^\s*theory\s+([A-Za-z_][\w'.]*)\b")
_DECL_RE = re.compile(
    r"(?m)^\s*"
    r"(?P<kind>lemma|theorem|corollary|proposition|definition)\b"
    r"\s*(?:\([^)]+\)\s*)?"
    r"(?:qualified\s+)?"
    r"(?P<name>[A-Za-z_][\w'.]*)"
    r"(?:\s*\[[^\]]*\])?"
    r"\s*(?::|where|=)",
)


@dataclass(frozen=True)
class ImportedTheoryFact:
    kind: str
    name: str
    theory: str
    line: int
    node_id: str
    uses: tuple[str, ...] = ()

    @property
    def qualified_name(self) -> str:
        return f"{self.theory}.{self.name}"


def import_theory_file(path: Path) -> list[ImportedTheoryFact]:
    text = path.read_text(encoding="utf-8")
    cleaned = strip_isabelle_comments(text)
    theory_match = _THEORY_RE.search(cleaned)
    theory = theory_match.group(1) if theory_match else path.stem
    matches = list(_DECL_RE.finditer(cleaned))
    raw_facts: list[ImportedTheoryFact] = []
    used_ids: set[str] = set()
    for match in matches:
        name = match.group("name")
        line = cleaned.count("\n", 0, match.start()) + 1
        node_id = _unique_node_id(_node_id(theory, name), used_ids)
        raw_facts.append(
            ImportedTheoryFact(
                kind=match.group("kind"),
                name=name,
                theory=theory,
                line=line,
                node_id=node_id,
            )
        )
    facts: list[ImportedTheoryFact] = []
    for index, fact in enumerate(raw_facts):
        start = matches[index].end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(cleaned)
        snippet = cleaned[start:end]
        uses = tuple(_infer_uses(snippet, raw_facts[:index]))
        facts.append(
            ImportedTheoryFact(
                kind=fact.kind,
                name=fact.name,
                theory=fact.theory,
                line=fact.line,
                node_id=fact.node_id,
                uses=uses,
            )
        )
    return facts


def render_imported_blueprint(
    facts: list[ImportedTheoryFact], *, project_name: str | None = None
) -> str:
    title = project_name or "Imported Isabelle theory"
    lines = [
        f"# {title}",
        "",
        "<!-- Generated by `isabelle-blueprint import-theory`.",
        "     This is a best-effort import of top-level declarations; review statements, "
        "dependencies, and proof sketches before relying on it. -->",
        "",
    ]
    for fact in facts:
        uses_lines: list[str] = []
        if fact.uses:
            uses_lines = ["uses:", *[f"  - {node_id}" for node_id in fact.uses]]
        lines.extend(
            [
                f"::: {fact.kind} {{#{fact.node_id}}}",
                f"title: {_title(fact.name)}",
                f"isabelle: {fact.qualified_name}",
                *uses_lines,
                "status:",
                "  blueprint: stub",
                "  formal: named",
                ":::",
                "",
                f"<!-- Imported from `{fact.theory}` line {fact.line}. "
                "Add the informal statement here. -->",
                "",
                "## Proof",
                "",
                "<!-- Add the informal proof sketch here. -->",
                ":::",
                "",
            ]
        )
    return "\n".join(lines)


def imported_theory_review(facts: list[ImportedTheoryFact]) -> dict[str, object]:
    """Return review metadata for best-effort theory imports."""

    return {
        "schema_version": 1,
        "facts": [
            {
                "node_id": fact.node_id,
                "kind": fact.kind,
                "name": fact.name,
                "qualified_name": fact.qualified_name,
                "theory": fact.theory,
                "line": fact.line,
                "suggested_uses": list(fact.uses),
            }
            for fact in facts
        ],
        "notes": [
            "Dependencies are inferred from references to earlier top-level facts.",
            "Review generated statements, suggested dependencies, and proof sketches "
            "before relying on them.",
        ],
    }


def strip_isabelle_comments(text: str) -> str:
    """Remove nested ``(* ... *)`` comments while preserving line numbers."""

    out: list[str] = []
    depth = 0
    i = 0
    in_string = False
    while i < len(text):
        two = text[i : i + 2]
        char = text[i]
        if depth == 0 and char == '"':
            in_string = not in_string
            out.append(char)
            i += 1
            continue
        if not in_string and two == "(*":
            depth += 1
            out.extend("  ")
            i += 2
            continue
        if depth > 0:
            if two == "(*":
                depth += 1
                out.extend("  ")
                i += 2
            elif two == "*)":
                depth -= 1
                out.extend("  ")
                i += 2
            else:
                out.append("\n" if char == "\n" else " ")
                i += 1
            continue
        out.append(char)
        i += 1
    return "".join(out)


def _node_id(theory: str, name: str) -> str:
    raw = f"{theory}-{name}".replace("_", "-")
    return re.sub(r"[^0-9A-Za-z-]+", "-", raw).strip("-").lower() or "imported-node"


def _unique_node_id(node_id: str, used: set[str]) -> str:
    candidate = node_id
    index = 2
    while candidate in used:
        candidate = f"{node_id}-{index}"
        index += 1
    used.add(candidate)
    return candidate


def make_node_id(theory: str, name: str, used: set[str]) -> str:
    """Return a unique, slugified blueprint node id for ``theory.name``.

    ``used`` is mutated to record the returned id, so repeated calls produce
    distinct ids. Shared with the source-index importer so both code paths use
    the same id convention.
    """
    return _unique_node_id(_node_id(theory, name), used)


def _infer_uses(snippet: str, previous: list[ImportedTheoryFact]) -> list[str]:
    uses: list[str] = []
    for fact in previous:
        if _mentions_fact(snippet, fact.name) or _mentions_fact(snippet, fact.qualified_name):
            uses.append(fact.node_id)
    return uses


def _mentions_fact(text: str, fact_name: str) -> bool:
    escaped = re.escape(fact_name)
    return bool(re.search(rf"(?<![\w'.]){escaped}(?![\w'.])", text))


def _title(name: str) -> str:
    text = re.sub(r"[_\-]+", " ", name).strip()
    return text[:1].upper() + text[1:] if text else "Imported fact"
