"""Generate an Isabelle theory that exercises every referenced fact.

The generated theory looks like::

    theory Blueprint_Check
      imports
        "Main"
        "Pythagoras.Triangles"
        "Pythagoras.Pythagoras"
    begin

    (* === Triangles === *)
    ML \\<open>val _ = Thm.prop_of @{thm Triangles.right_angle_def}\\<close>

    (* === Pythagoras === *)
    ML \\<open>val _ = Thm.prop_of @{thm Pythagoras.pythagoras_thm}\\<close>

    end

Running ``isabelle build`` on a session that includes this theory will fail if
any ``@{thm name}`` antiquotation cannot be resolved. For resolved facts the
generated ML also prints a machine-readable status line based on
``Thm_Deps.has_skip_proof`` and ``Thm_Deps.all_oracles`` so the Python checker
can distinguish merely-found facts from trusted ``proved`` facts.
"""

from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass

from isabelle_blueprint.model.node import BlueprintNode
from isabelle_blueprint.model.project import BlueprintProject


@dataclass(frozen=True)
class FactReference:
    """An (id, theory, fact-name) triple to render in the check theory."""

    node_id: str
    theory: str
    fact: str
    session: str | None = None


def group_facts_by_theory(
    project: BlueprintProject,
    *,
    include_node_ids: set[str] | None = None,
) -> dict[str, list[FactReference]]:
    """Return references grouped by their owning theory.

    Nodes without a resolvable ``isabelle:`` reference are skipped. When
    ``include_node_ids`` is provided, only nodes whose id is in that set are
    considered (used by the incremental checker to generate a wrapper theory
    that contains only the subset of facts that actually need re-checking).
    """
    grouped: dict[str, list[FactReference]] = defaultdict(list)
    for node in project.nodes:
        if include_node_ids is not None and node.id not in include_node_ids:
            continue
        ref = _resolve(node)
        if ref is None:
            continue
        grouped[ref.theory].append(ref)
    return dict(grouped)


def _resolve(node: BlueprintNode) -> FactReference | None:
    fact = node.isabelle.fact
    theory = node.isabelle.theory
    if not fact:
        return None
    if theory is None and "." in fact:
        theory = fact.rsplit(".", 1)[0]
    if theory is None:
        # No theory we can import; the checker would just fail.
        return None
    return FactReference(node_id=node.id, theory=theory, fact=fact, session=node.isabelle.session)


def generate_check_theory(
    project: BlueprintProject,
    *,
    theory_name: str = "Blueprint_Check",
    extra_imports: list[str] | None = None,
    emit_proof_status: bool = True,
    default_import_session: str | None = None,
    proof_status_file: str = "Blueprint_Proof_Status.tsv",
    generation_nonce: str | None = None,
    include_node_ids: set[str] | None = None,
) -> str:
    """Return the source of an Isabelle theory that references every fact.

    When ``include_node_ids`` is provided, only those nodes contribute facts to
    the generated theory. This is used by the incremental checker to ship a
    reduced wrapper containing just the changed/uncached subset.
    """
    grouped = group_facts_by_theory(project, include_node_ids=include_node_ids)
    imports = sorted(
        {
            _import_name(ref, default_import_session=default_import_session)
            for refs in grouped.values()
            for ref in refs
        }
    )
    if extra_imports:
        imports.extend(extra_imports)
    if not imports:
        imports = ["Main"]

    lines: list[str] = []
    lines.append(f"theory {theory_name}")
    lines.append("  imports")
    for imp in imports:
        lines.append(f'    "{imp}"')
    lines.append("begin")
    lines.append("")
    lines.append("(* Auto-generated by IsabelleBlueprint. Do not edit by hand. *)")
    if generation_nonce:
        lines.append(f"(* Check nonce: {_comment_escape(generation_nonce)} *)")
    lines.append("")
    proof_refs: list[FactReference] = []
    for theory in sorted(grouped):
        refs = grouped[theory]
        lines.append(f"(* === {theory} === *)")
        for ref in sorted(refs, key=lambda r: r.fact):
            if emit_proof_status:
                proof_refs.append(ref)
            else:
                lines.append(
                    f"ML \\<open>val _ = Thm.prop_of @{{thm {ref.fact}}}\\<close>  "
                    f"(* {ref.node_id} *)"
                )
        lines.append("")
    if emit_proof_status and proof_refs:
        lines.extend(
            _proof_status_ml_block(
                sorted(proof_refs, key=lambda r: (r.theory, r.fact)),
                proof_status_file=proof_status_file,
            )
        )
        lines.append("")
    lines.append("end")
    return "\n".join(lines) + "\n"


def _import_name(ref: FactReference, *, default_import_session: str | None = None) -> str:
    session = ref.session or default_import_session
    if not session:
        return ref.theory
    if ref.theory.startswith(f"{session}."):
        return ref.theory
    return f"{session}.{ref.theory}"


def _proof_status_ml_block(refs: list[FactReference], *, proof_status_file: str) -> list[str]:
    path = _ml_string(proof_status_file)
    row_lines = []
    for ref in refs:
        row_lines.append(
            f"    ({_ml_string(ref.node_id)}, {_ml_string(ref.fact)}, @{{thm {ref.fact}}})"
        )
    rows = ",\n".join(row_lines)
    return [
        "ML \\<open>",
        "let",
        "  val rows = [",
        rows,
        "  ]",
        "  fun render (node_id, fact, thm) =",
        "    let",
        "      val thms = [thm]",
        "      val _ = Thm.prop_of thm",
        "      val oracles = Thm_Deps.all_oracles thms",
        "        |> map (fn ((name, _), _) => name)",
        "      val has_skip = Thm_Deps.has_skip_proof thms",
        '      val status = if has_skip orelse not (null oracles) then "tainted" else "proved"',
        '      val oracle_text = if null oracles then "-" else space_implode "," oracles',
        "    in",
        '      "ISABELLE_BLUEPRINT_FACT\\t" ^ node_id ^ "\\t" ^ fact ^ "\\t" ^ '
        'status ^ "\\t" ^ oracle_text',
        "    end",
        "in",
        f'  File.write (Path.explode {path}) (cat_lines (map render rows) ^ "\\n")',
        "end",
        "\\<close>",
    ]


def _ml_string(text: str) -> str:
    escaped = (
        text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _root_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _comment_escape(text: str) -> str:
    return text.replace("*)", "* )")


# ---------------------------------------------------------------------------
# Wrapper-session ROOT generation (shared by the checker and sledgehammer-run).
# ---------------------------------------------------------------------------


def generate_check_root(
    session_name: str,
    *,
    wrapper_name: str = "Blueprint_Check_Wrapper",
    theory_name: str = "Blueprint_Check",
    session_deps: list[str] | None = None,
) -> str:
    """Return the contents of a ROOT file that wraps the user's session.

    The wrapper session inherits from ``session_name`` and adds an auto-generated
    theory (``Blueprint_Check`` by default, or ``Blueprint_Sledgehammer`` for the
    sledgehammer-run flow). Writing this file alongside the generated ``.thy`` in
    the build directory lets ``isabelle build -d <build_dir>`` resolve the theory
    without modifying the user's own ROOT file.
    """
    deps = sorted({dep for dep in session_deps or [] if dep and dep != session_name})
    lines = [f"session {_root_string(wrapper_name)} = {_root_string(session_name)} +"]
    if deps:
        lines.append("  sessions")
        lines.extend(f"    {_root_string(dep)}" for dep in deps)
    lines.extend(["  theories", f"    {theory_name}"])
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Sledgehammer-run theory generation.
# ---------------------------------------------------------------------------


def _thy_inner_string(text: str) -> str:
    """Escape *text* for embedding inside an ML/inner-syntax double-quoted string.

    The goal is written verbatim as ``Syntax.read_prop ctxt "<goal>"``. Only the
    double-quote is escaped (``"`` -> ``\\"``) so it cannot terminate the ML
    string literal early.

    Crucially, backslashes are *not* doubled. An Isabelle goal contains symbol
    tokens such as ``\\<forall>`` or ``\\<le>`` written with a single backslash;
    Isabelle's symbol layer rewrites ``\\<forall>`` to the Unicode glyph
    *before* the SML lexer sees the string. Doubling the backslash would leave a
    stray ``\\`` in front of that glyph, which SML then rejects as a "bad escape
    character" -- breaking the build for essentially every realistic goal. (A
    bare backslash that is not part of a ``\\<...>`` symbol is not valid Isabelle
    inner syntax in the first place, so there is nothing useful to escape it to.)

    Control whitespace (CR/LF/TAB), which a goal sourced from a multi-line or
    space-padded YAML value can carry, is collapsed to single spaces: a raw
    newline inside the ML string literal would produce invalid SML, while
    Isabelle inner syntax treats runs of whitespace as insignificant, so the
    parsed proposition is unchanged.
    """
    text = re.sub(r"[\r\n\t]+", " ", text)
    return text.replace('"', '\\"')


def sledgehammer_imports(
    project: BlueprintProject,
    *,
    node_id: str,
    default_import_session: str | None = None,
) -> list[str]:
    """Return the sorted import list for the one-node sledgehammer wrapper.

    Always includes ``Main``. Adds the target node's own theory (when it has a
    resolvable Isabelle reference) plus the theories of its declared dependency
    nodes, so the sledgehammer context can see the relevant definitions/lemmas.
    """
    by_id = project.by_id()
    node = by_id.get(node_id)
    imports: set[str] = {"Main"}
    if node is None:
        return sorted(imports)
    relevant = [node]
    for dep_id in node.uses:
        dep = by_id.get(dep_id)
        if dep is not None:
            relevant.append(dep)
    for n in relevant:
        ref = _resolve(n)
        if ref is not None:
            imports.add(_import_name(ref, default_import_session=default_import_session))
    return sorted(imports)


def generate_sledgehammer_theory(
    project: BlueprintProject,
    *,
    node_id: str,
    result_file: str,
    timeout: float,
    theory_name: str = "Blueprint_Sledgehammer",
    provers: str = "e z3",
    default_import_session: str | None = None,
    nonce: str | None = None,
) -> str | None:
    """Return the source of a wrapper theory that runs sledgehammer on one node.

    The goal source is chosen per the node:

    * if the node carries an explicit ``goal`` proposition, it is parsed with
      ``Syntax.read_prop`` in the wrapper context, and
    * otherwise the node's named Isabelle ``fact`` is re-proved: its statement is
      recovered via ``Thm.prop_of (Proof_Context.get_thm ctxt "<fact>")``.

    Returns ``None`` when the node has neither a ``goal`` nor a resolvable fact
    (there is nothing to attempt, so no theory should be built).
    """
    node = project.by_id().get(node_id)
    if node is None:
        return None

    goal = (node.goal or "").strip()
    ref = _resolve(node)
    if goal:
        goal_source = f'Syntax.read_prop ctxt "{_thy_inner_string(goal)}"'
    elif ref is not None:
        goal_source = f"Thm.prop_of (Proof_Context.get_thm ctxt {_ml_string(ref.fact)})"
    else:
        return None

    imports = sledgehammer_imports(
        project, node_id=node_id, default_import_session=default_import_session
    )
    timeout_secs = max(1, int(round(timeout)))

    lines: list[str] = []
    lines.append(f"theory {theory_name}")
    lines.append("  imports")
    for imp in imports:
        lines.append(f'    "{imp}"')
    lines.append("begin")
    lines.append("")
    lines.append("(* Auto-generated by IsabelleBlueprint. Do not edit by hand. *)")
    lines.append(f"(* Sledgehammer target node: {_comment_escape(node_id)} *)")
    if nonce:
        # Force ``isabelle build`` to re-execute the ML on every run: an unchanged
        # wrapper session is cached in the global heap and the sledgehammer ML
        # (and thus the result file) would never run again. A fresh nonce per run
        # perturbs the theory source so the session is always rebuilt.
        lines.append(f"(* Run nonce: {_comment_escape(nonce)} *)")
    lines.append("")
    lines.extend(
        _sledgehammer_ml_block(
            goal_source=goal_source,
            result_file=result_file,
            provers=provers,
            timeout_secs=timeout_secs,
        )
    )
    lines.append("")
    lines.append("end")
    return "\n".join(lines) + "\n"


def _sledgehammer_ml_block(
    *,
    goal_source: str,
    result_file: str,
    provers: str,
    timeout_secs: int,
) -> list[str]:
    """Render the ML block that runs sledgehammer and writes a result TSV.

    Batch ``isabelle build`` suppresses sledgehammer/``writeln`` stdout, so the
    outcome is written to *result_file* and read back by the Python engine -- the
    same pattern the proof-status checker uses.
    """
    result_path = _ml_string(result_file)
    return [
        "ML \\<open>",
        "let",
        "  fun strip s = XML.content_of (YXML.parse_body s)",
        "  fun hammer ctxt goal =",
        "    let",
        "      val thy = Proof_Context.theory_of ctxt",
        "      val state = Proof.theorem NONE (K I) [[(goal, [])]] ctxt",
        "      val params = Sledgehammer_Commands.default_params thy",
        f'        [("provers", {_ml_string(provers)}), '
        f'("timeout", {_ml_string(str(timeout_secs))})]',
        "      val (ok, (outcome, proof)) =",
        "        Sledgehammer.run_sledgehammer params Sledgehammer_Prover.Normal NONE 1",
        "          Sledgehammer_Fact.no_fact_override state",
        '    in (if ok then "SOME" else "NONE") ^ "\\t" ^',
        '       Sledgehammer.short_string_of_sledgehammer_outcome outcome ^ "\\t" ^ '
        "strip proof end",
        "  val ctxt = @{context}",
        f"  val goal = {goal_source}",
        "  val result = hammer ctxt goal",
        "in",
        f'  File.write (Path.explode {result_path}) (result ^ "\\n")',
        "end",
        "\\<close>",
    ]
