"""Best-effort import of Isabelle theory declarations into blueprint nodes."""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

DECLARATION_KINDS = ("lemma", "theorem", "corollary", "proposition", "definition")
_THEORY_RE = re.compile(r"(?m)^\s*theory\s+([A-Za-z_][\w'.]*)\b")
_DECL_RE = re.compile(
    r"(?m)^\s*"
    r"(?P<kind>lemma|theorem|corollary|proposition|definition)\b"
    r"\s*(?:\([^)]+\)\s*)?"
    r"(?:qualified\s+)?"
    r"(?P<name>[A-Za-z_][\w'.]*)"
    r"(?:\s*\[[^\]]*\])?"
    r"\s*(?::|where|=)",
)


@dataclass(frozen=True)
class ImportedTheoryFact:
    kind: str
    name: str
    theory: str
    line: int
    node_id: str

    @property
    def qualified_name(self) -> str:
        return f"{self.theory}.{self.name}"


def import_theory_file(path: Path) -> list[ImportedTheoryFact]:
    text = path.read_text(encoding="utf-8")
    cleaned = strip_isabelle_comments(text)
    theory_match = _THEORY_RE.search(cleaned)
    theory = theory_match.group(1) if theory_match else path.stem
    facts: list[ImportedTheoryFact] = []
    used_ids: set[str] = set()
    for match in _DECL_RE.finditer(cleaned):
        name = match.group("name")
        line = cleaned.count("\n", 0, match.start()) + 1
        node_id = _unique_node_id(_node_id(theory, name), used_ids)
        facts.append(
            ImportedTheoryFact(
                kind=match.group("kind"),
                name=name,
                theory=theory,
                line=line,
                node_id=node_id,
            )
        )
    return facts


def render_imported_blueprint(facts: list[ImportedTheoryFact], *, project_name: str | None = None) -> str:
    title = project_name or "Imported Isabelle theory"
    lines = [
        f"# {title}",
        "",
        "<!-- Generated by `isabelle-blueprint import-theory`.",
        "     This is a best-effort import of top-level declarations; review statements, dependencies, and proof sketches before relying on it. -->",
        "",
    ]
    for fact in facts:
        lines.extend(
            [
                f"::: {fact.kind} {{#{fact.node_id}}}",
                f"title: {_title(fact.name)}",
                f"isabelle: {fact.qualified_name}",
                "status:",
                "  blueprint: stub",
                "  formal: named",
                ":::",
                "",
                f"<!-- Imported from `{fact.theory}` line {fact.line}. Add the informal statement here. -->",
                "",
                "## Proof",
                "",
                "<!-- Add the informal proof sketch here. -->",
                ":::",
                "",
            ]
        )
    return "\n".join(lines)


def strip_isabelle_comments(text: str) -> str:
    """Remove nested ``(* ... *)`` comments while preserving line numbers."""

    out: list[str] = []
    depth = 0
    i = 0
    in_string = False
    while i < len(text):
        two = text[i : i + 2]
        char = text[i]
        if depth == 0 and char == '"':
            in_string = not in_string
            out.append(char)
            i += 1
            continue
        if not in_string and two == "(*":
            depth += 1
            out.extend("  ")
            i += 2
            continue
        if depth > 0:
            if two == "(*":
                depth += 1
                out.extend("  ")
                i += 2
            elif two == "*)":
                depth -= 1
                out.extend("  ")
                i += 2
            else:
                out.append("\n" if char == "\n" else " ")
                i += 1
            continue
        out.append(char)
        i += 1
    return "".join(out)


def _node_id(theory: str, name: str) -> str:
    raw = f"{theory}-{name}".replace("_", "-")
    return re.sub(r"[^0-9A-Za-z-]+", "-", raw).strip("-").lower() or "imported-node"


def _unique_node_id(node_id: str, used: set[str]) -> str:
    candidate = node_id
    index = 2
    while candidate in used:
        candidate = f"{node_id}-{index}"
        index += 1
    used.add(candidate)
    return candidate


def _title(name: str) -> str:
    text = re.sub(r"[_\-]+", " ", name).strip()
    return text[:1].upper() + text[1:] if text else "Imported fact"
