"""Generate an Isabelle theory that exercises every referenced fact.

The generated theory looks like::

    theory Blueprint_Check
      imports
        "Main"
        "Pythagoras.Triangles"
        "Pythagoras.Pythagoras"
    begin

    (* === Triangles === *)
    ML \\<open>val _ = Thm.prop_of @{thm Triangles.right_angle_def}\\<close>

    (* === Pythagoras === *)
    ML \\<open>val _ = Thm.prop_of @{thm Pythagoras.pythagoras_thm}\\<close>

    end

Running ``isabelle build`` on a session that includes this theory will fail if
any ``@{thm name}`` antiquotation cannot be resolved, giving us a coarse but
reliable "fact exists" check. Detection of ``sorry``/oracles is intentionally
deferred to a later milestone (roadmap section 6).
"""
from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass

from isabelle_blueprint.model.node import BlueprintNode
from isabelle_blueprint.model.project import BlueprintProject


@dataclass(frozen=True)
class FactReference:
    """An (id, theory, fact-name) triple to render in the check theory."""

    node_id: str
    theory: str
    fact: str


def group_facts_by_theory(project: BlueprintProject) -> dict[str, list[FactReference]]:
    """Return references grouped by their owning theory.

    Nodes without a resolvable ``isabelle:`` reference are skipped.
    """
    grouped: dict[str, list[FactReference]] = defaultdict(list)
    for node in project.nodes:
        ref = _resolve(node)
        if ref is None:
            continue
        grouped[ref.theory].append(ref)
    return dict(grouped)


def _resolve(node: BlueprintNode) -> FactReference | None:
    fact = node.isabelle.fact
    theory = node.isabelle.theory
    if not fact:
        return None
    if theory is None and "." in fact:
        theory = fact.rsplit(".", 1)[0]
    if theory is None:
        # No theory we can import; the checker would just fail.
        return None
    return FactReference(node_id=node.id, theory=theory, fact=fact)


def generate_check_theory(
    project: BlueprintProject,
    *,
    theory_name: str = "Blueprint_Check",
    extra_imports: list[str] | None = None,
) -> str:
    """Return the source of an Isabelle theory that references every fact."""
    grouped = group_facts_by_theory(project)
    imports = sorted({thy for thy in grouped})
    if extra_imports:
        imports.extend(extra_imports)
    if not imports:
        imports = ["Main"]

    lines: list[str] = []
    lines.append(f"theory {theory_name}")
    lines.append("  imports")
    for imp in imports:
        lines.append(f'    "{imp}"')
    lines.append("begin")
    lines.append("")
    lines.append("(* Auto-generated by IsabelleBlueprint. Do not edit by hand. *)")
    lines.append("")
    for theory in sorted(grouped):
        refs = grouped[theory]
        lines.append(f"(* === {theory} === *)")
        for ref in sorted(refs, key=lambda r: r.fact):
            lines.append(
                f"ML \\<open>val _ = Thm.prop_of @{{thm {ref.fact}}}\\<close>  (* {ref.node_id} *)"
            )
        lines.append("")
    lines.append("end")
    return "\n".join(lines) + "\n"


def generate_check_root(
    session_name: str,
    *,
    wrapper_name: str = "Blueprint_Check_Wrapper",
    theory_name: str = "Blueprint_Check",
) -> str:
    """Return the contents of a ROOT file that wraps the user's session.

    The wrapper session inherits from ``session_name`` and adds the auto-generated
    ``Blueprint_Check`` theory. Writing this file alongside ``Blueprint_Check.thy``
    in the build directory lets ``isabelle build -d <build_dir>`` resolve the
    theory without modifying the user's own ROOT file.
    """
    return (
        f'session "{wrapper_name}" = "{session_name}" +\n'
        f"  theories\n"
        f"    {theory_name}\n"
    )
